# Generated by Django 6.0.5 on 2026-06-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('phonepe', 'PhonePe'), ('upi', 'Direct UPI')], default='phonepe', max_length=10),
        ),
    ]
